package archit.common.visitors;

public enum Operators {
    // Arithmetic
    ADD_NUMBERS, ADD_REALS,
    SUBTRACT_NUMBERS, SUBTRACT_REALS,
    MULTIPLY_NUMBERS, MULTIPLY_REALS,
    DIVIDE_NUMBERS, DIVIDE_REALS,
    MODULO, POWER_NUMBERS, POWER_REALS,

    // Comparison
    EQUALS, NOT_EQUALS,
    GREATER_NUMBERS, GREATER_EQUALS_NUMBERS,
    GREATER_REALS, GREATER_EQUALS_REALS,
    LESS_NUMBERS, LESS_EQUALS_NUMBERS,
    LESS_REALS, LESS_EQUALS_REALS,

    // Logical
    AND, OR, NOT,

    // Indexing / Access
    LIST_INDEX, MAP_GET,

    // Unary minus
    NEGATE_NUMBER, NEGATE_REAL,

    // Assignment
    ASSIGN,
    ASSIGN_ADD_NUMBERS, ASSIGN_ADD_REALS,
    ASSIGN_SUBTRACT_NUMBERS, ASSIGN_SUBTRACT_REALS,
    ASSIGN_MULTIPLY_NUMBERS, ASSIGN_MULTIPLY_REALS,
    ASSIGN_DIVIDE_NUMBERS, ASSIGN_DIVIDE_REALS,
    ASSIGN_MODULO, ASSIGN_POWER_NUMBERS, ASSIGN_POWER_REALS,
}
